# COM400 Mathematics for Computing Coursework

## Instructions

You can use and import libraries that were used in the COM400 labs.

It is left to your own judgement as to how many decimal places you should round any numerical answers.

Further details are found in the Notebook.

**This coursework is worth 50% of the overall module mark.**

**<font color=red>Deadline: 5:00 pm, Friday 20th November 2020</font>**

**<font color=red>This is an individual assignment: University regulations on plagiarism will apply.</font>**
  
**The total number of marks available in this assignment is 100.**

**Enter your solutions directly into this Jupyter notebook.**

For each question, you should provide your answer **in the cell immediately below the question**.

If a question requires a **numerical answer**, your cell should include python code carrying out the relevant calculations, and include a `print` statement to make clear what your answer to the question is. 

If a question requires a **graphical plot**, your cell should include python code that results in the required plot being printed to screen.

**For example,** if a question asked : **What is the value of $\sqrt{500}$ ?**

then you should present your solution in a cell as follows:

In [1]:
# code performing your calculations
# ...
# ...
ans = 500**0.5
print("square root of 500 = ", ans)

square root of 500 =  22.360679774997898


**You need to submit BOTH of the following via Blackboard before the deadline:**
  1. **This Jupyter notebook (containing your solutions), AND**
  2. **A pdf of this Jupyter notebook (containing your solutions).**
  
 You can convert your Jupyter notebook to pdf by:
 - printing directly from your browser to pdf
 - if the above does not work in your browser, go to File-> Download As... -> HTML (.html). Then open the html file in Goggle chrome, and print from chrome to pdf.

## <font color = blue>Question 1: Matrices</font>

### <font color = blue>Question 1 Part A</font>

Three matrices $\mathbf{A}$, $\mathbf{B}$ and $\mathbf{C}$ and a vector $\mathbf{y}$ are given as

$\mathbf{A} = \begin{bmatrix} 6 & 1 & 2 & -3 \\ 4 & 0 & -2 & 3 \\ 1 & -3 & 0 & 2 \end{bmatrix}, \mathbf{B} = \begin{bmatrix} 2 & 0 & 1 \\ 6 & 2 & 0 \\ 4 & 2 & -1 \end{bmatrix}, \mathbf{C} = \begin{bmatrix} 4 & 0 & 1 & 2 \\ 3 & -2 & 0 & 1 \\ 0 & 1 & 5 & -3 \\ -2 & 2 & 1 & 4 \end{bmatrix}, \mathbf{y} = \begin{bmatrix} 2 \\ -3 \\ 2 \\ 4\end{bmatrix}$

Provide solutions to each of the following questions or else explain why it is not possible:

In [1]:
# ********-------Run this at beginning--------******** 

import numpy as np
print(np.__version__)

1.19.4


**i)**	Define $\mathbf{A}$, $\mathbf{B}$, $\mathbf{C}$ and $\mathbf{y}$ in Python, and print each to screen.	&emsp; **\[4 marks\]**

In [60]:
A = np.array([[6,1,2,-3],[4,0,-2,3],[1,-3,0,2]])
print("A \n", A)

A 
 [[ 6  1  2 -3]
 [ 4  0 -2  3]
 [ 1 -3  0  2]]


In [61]:
B = np.array([[2,0,1],[6,2,0],[4,2,-1]])
print("B \n", B)

B 
 [[ 2  0  1]
 [ 6  2  0]
 [ 4  2 -1]]


In [62]:
C = np.array([[4,0,1,2],[3,-2,0,1],[0,1,5,-3],[-2,2,1,4]])
print("C \n", C)

C 
 [[ 4  0  1  2]
 [ 3 -2  0  1]
 [ 0  1  5 -3]
 [-2  2  1  4]]


In [63]:
y = np.array([[2],[-3],[2],[4]])
print("y \n", y)

y 
 [[ 2]
 [-3]
 [ 2]
 [ 4]]


**ii)** $\mathbf{A}^T\mathbf{B}$ &emsp; **\[2 marks\]**

In [25]:
print("A^TB \n",A.T @ B)

A^TB 
 [[ 40  10   5]
 [-10  -6   4]
 [ -8  -4   2]
 [ 20  10  -5]]


**iii)** $\mathbf{Ay}$ &emsp; **\[2 marks\]**

In [14]:
print("Ay\n",A @ y)

Ay
 [[ 1]
 [16]
 [19]]


**iv)** $\mathbf{CA}$ &emsp; **\[2 marks\]**

In [17]:
print("Order of C",C.shape)
print("Order of A",A.shape)
print("Order of C and A is incompatible for multiplication.")

Order of C (4, 4)
Order of A (3, 4)
Order of C and A is incompatible for multiplication.


**v)** $\mathbf{C}^{10}$ &emsp; **\[2 marks\]**

In [100]:
print("C^10\n", np.linalg.matrix_power(C,10))

C^10
 [[ 9360925 -1586650  6654085 -8200163]
 [ 4031932  -797920  2727348 -3845916]
 [ 8826598   182727  9184453 -4044841]
 [ 1406889  -204534  -684803   608893]]


**vi)** $\mathbf{B}^{-1}$ &emsp; **\[2 marks\]**

In [102]:
# to the power of -1
print("B^-1\n", np.linalg.matrix_power(B,-1))

print("\n or\n")

# inverse
print("B^-1\n", np.linalg.inv(B))

B^-1
 [[-2.25179981e+15  2.25179981e+15 -2.25179981e+15]
 [ 6.75539944e+15 -6.75539944e+15  6.75539944e+15]
 [ 4.50359963e+15 -4.50359963e+15  4.50359963e+15]]

 or

B^-1
 [[-2.25179981e+15  2.25179981e+15 -2.25179981e+15]
 [ 6.75539944e+15 -6.75539944e+15  6.75539944e+15]
 [ 4.50359963e+15 -4.50359963e+15  4.50359963e+15]]


**vii)**  $\mathbf{C}^{−1}$ &emsp; **\[2 marks\]**

In [101]:
# to the power of -1
print("C^-1\n", np.linalg.matrix_power(C,-1))

print("\n or\n")

# inverse
print("C^-1\n", np.linalg.inv(C))

C^-1
 [[ 0.29569892 -0.15053763 -0.03225806 -0.1344086 ]
 [ 0.42473118 -0.6344086  -0.06451613 -0.10215054]
 [-0.10752688  0.23655914  0.19354839  0.13978495]
 [-0.03763441  0.1827957  -0.03225806  0.19892473]]

 or

C^-1
 [[ 0.29569892 -0.15053763 -0.03225806 -0.1344086 ]
 [ 0.42473118 -0.6344086  -0.06451613 -0.10215054]
 [-0.10752688  0.23655914  0.19354839  0.13978495]
 [-0.03763441  0.1827957  -0.03225806  0.19892473]]


**viii)** $\mathbf{A}\mathbf{A}^T - \mathbf{B}$ &emsp; **\[2 marks\]**

In [22]:
print("AA^T-B\n",A @ A.T - B)

AA^T-B
 [[48 11 -4]
 [ 5 27 10]
 [-7  8 15]]


**ix)** By identifying two suitable matrices from $\mathbf{A}$, $\mathbf{B}$, $\mathbf{C}$, and $\mathbf{y}$ demonstrate that taking the transpose of the product of the first one times the second one is equal to the product of the transpose of the second one times the transpose of the first one \[$(\mathbf{XY})^T = \mathbf{Y}^T\mathbf{X}^T$\]. &emsp; **\[2 marks\]**

In [78]:
first = A @ C
second = C.T @ A.T

print("(AC)𝑇 = A^TC^T")
print(first.T,"\n")
print(second)
print("\n Therefore (AC)T = A^TC^T")

(AC)𝑇 = A^TC^T
[[33 10 -9]
 [-6  4 10]
 [13 -3  3]
 [-5 26  7]] 

[[33 10 -9]
 [-6  4 10]
 [13 -3  3]
 [-5 26  7]]

 Therefore (AC)T = A^TC^T


### <font color=blue>Question 1 Part B</font>

Determine the solution to the following equations, i.e. determine the values of $w, x, y, z$. &emsp; **\[10 marks\]**

\begin{align}
w + 3x + 2y - z & = 3 \\
2w + 3y + 3z & = 1 \\
3w + x - y & = -1\\
2x + 3z & = 4
\end{align}

Mark breakdown: 
- 3 marks for defining matrix, 
- 2 for defining vector, 
- 2 for calculating solution, 
- 1 for checking answer, 
- 2 for displaying values of $w,x,y,z$

In [60]:
MatrixD = np.array([[1,3,2,-1],[2,0,3,3],[3,1,-1,0],[0,2,0,3]])
MatrixE = np.array([[3,1,-1,4]]).T

print("Matrix\n",MatrixD)
print("\nVector\n",MatrixE)

MatrixF = np.linalg.solve(MatrixD,MatrixE)
print("\nSolution\n", MatrixF)

print("\nValues")
w = MatrixF[0,0]
x = MatrixF[1,0]
y = MatrixF[2,0]
z = MatrixF[3,0]

print("w =", w)
print("x =", x)
print("y =", y)
print("z =", z)

check1 = w + (3 * x) + (2 * y) - z
check2 = (2 * w) + (3 * y) + (3 * z)
check3 = (3 * w) + x - y
check4 = (2 * x) + (3 * z)

print("\nCheck")
print("w + 3x + 2y - z = ",np.single(check1))
print("2w + 3y + 3z = ",np.single(check2))
print("3w + x - y = ",np.single(check3))
print("2x + 3z = ",np.single(check4))


Matrix
 [[ 1  3  2 -1]
 [ 2  0  3  3]
 [ 3  1 -1  0]
 [ 0  2  0  3]]

Vector
 [[ 3]
 [ 1]
 [-1]
 [ 4]]

Solution
 [[-0.65662651]
 [ 1.22289157]
 [ 0.25301205]
 [ 0.51807229]]

Values
w = -0.6566265060240963
x = 1.2228915662650601
y = 0.2530120481927711
z = 0.5180722891566264

Check
w + 3x + 2y - z =  3.0
2w + 3y + 3z =  1.0
3w + x - y =  -1.0
2x + 3z =  4.0


## <font color = blue>Question 2: Probability</font>

### <font color=blue>Question 2 Part A</font>

Suppose there are two bags, each containing 100 balls. Bag 1 has 30 white balls and 70 black balls, while bag 2 has 60 white balls and 40 black balls. Suppose this information is known to both Alice and Bob. Alice selects one of the bags randomly (by tossing a coin) and then proceeds to select a ball randomly from that bag. She shows the selected ball to Bob, but does not tell him which bag it is from. Based on the information available to him, Bob must try determine which bag was selected.

Based on this scenario, answer the following questions.

**i)** Write code to simulate Alice's selection of one of the two bags. Store the choice in a variable called `bag` and print its value to show whether bag 1 or bag 2 was selected.  &emsp; **\[2 marks\]**

In [76]:
Coin = 0.5

# Heads = "1, 30 white balls and 70 black balls"
# Tails = "2, 60 white balls and 40 black balls"

Heads = 1
Tails = 2

random_bag = np.random.random()
result = ""

if random_bag < Coin:
    result = Heads
else:
    result = Tails

bag = result
print("Selected Bag", bag)

Selected Bag 1


**ii)** Write code to simulate Alice's selection of a ball from the selected bag. Store the selection in a variable called `colour` and print its value to show whether a white or a black ball was selected. (Note: the code should be written in such a way that the ball could be selected from either bag depending on the value of the `bag` variable coming from (i).)  &emsp; **\[4 marks\]**

In [77]:
# need to call random again otherwise
# would have to refresh previous code for different random value
random_ball = np.random.random()

if bag == 1:
    
    if random_ball <= 0.3:
        colour = "White Ball" 
    else:
        colour = "Black Ball"
        
elif bag == 2:
    
    if random_ball <= 0.6:
        colour = "White Ball" 
    else:
        colour = "Black Ball"
        
print("Selected Colour", colour)

Selected Colour White Ball


**iii)** Bob wants to work out the probability that the selected bag was bag 1 and the probability that it was bag 2. First, he decides to work out the total probability of the ball being a) white, and b) black. Provide code to determine these probabilities.  &emsp; **\[4 marks\]**

In [78]:
Coin = 0.5
bag_prob = Coin

prob_bag1_w = 0.3 
prob_bag2_w = 0.6

ball_w = prob_bag1_w * bag_prob + prob_bag2_w * bag_prob
print("Bag 1 White Ball Probability: {:.2f}".format(ball_w))
print("Bag 1 Black Ball Probability:", 1 - ball_w)

prob_bag1_b = 0.7
prob_bag2_b = 0.4

ball_b = prob_bag1_b * bag_prob + prob_bag2_b * bag_prob
print("Bag 2 White Ball Probability:", ball_b)
print("Bag 2 Black Ball Probability: {:0.2f}".format(1 - ball_b))

Bag 1 White Ball Probability: 0.45
Bag 1 Black Ball Probability: 0.55
Bag 2 White Ball Probability: 0.55
Bag 2 Black Ball Probability: 0.45


**iv)** Based on these probabilities, provide code for Bob to determine the probability that the selected bag was bag 1 and the probability that is was bag 2 using Bayes' theorem.  &emsp; **\[6 marks\]**

In [89]:
# Bayes theorem
prob_bag1 = (prob_bag1_w * bag_prob) / ball_w
prob_bag2 = 1.0 - prob_bag1
print("Bag 1 Probability: {:.2f}".format(prob_bag1))
print("Bag 2 Probability: {:.2f}".format(prob_bag2))

# Bayes theorem
prob_bag1_white = (prob_bag1_w * bag_prob) / ball_w
prob_bag2_white = 1.0 - prob_bag1_white
print("Bag 1 White Probability: {:.2f}".format(prob_bag1_white))
print("Bag 2 White Probability: {:.2f}".format(prob_bag2_white))

# Bayes theorem
prob_bag1_black = (prob_bag1_b * bag_prob) / ball_b
prob_bag2_black = 1.0 - prob_bag1_black
print("Bag 1 Black Probability: {:.2f}".format(prob_bag1_black))
print("Bag 2 Black Probability: {:.2f}".format(prob_bag2_black))

Bag 1 Probability: 0.33
Bag 2 Probability: 0.67
Bag 1 White Probability: 0.33
Bag 2 White Probability: 0.67
Bag 1 Black Probability: 0.64
Bag 2 Black Probability: 0.36


**v)** Suppose Alice replaces the ball in the bag and proceeds to select another ball at random. Based on the evidence available to Bob so far, provide code to enable him to determine the probability that this ball will be the same colour has the first one. (Note: you will need to allow for the possibility that the first ball was white or black.)  &emsp; **\[4 marks\]**

In [82]:
# Reset prior probabilities
prob_bag1_w = prob_bag1_white 
prob_bag2_w = prob_bag2_white

prob_bag1_b = prob_bag1_black
prob_bag2_b = prob_bag2_black

# Repeat the process

# Total Probability
ball_w = prob_bag1_w * bag_prob + prob_bag2_w * bag_prob

# Bayes Theorem
prob_bag1 = (prob_bag1_w * bag_prob) / ball_w
prob_bag2 = 1.0 - prob_bag1

print("Bag 1 Probability: {:.2f}".format(prob_bag1))
print("Bag 2 Probability: {:.2f}".format(prob_bag2))

# Bayes theorem
prob_bag1_white = (prob_bag1_w * bag_prob) / ball_w
prob_bag2_white = 1.0 - prob_bag1_white
print("Bag 1 White Probability: {:.2f}".format(prob_bag1_white))
print("Bag 2 White Probability: {:.2f}".format(prob_bag2_white))

# Total probability
ball_b = prob_bag1_b * bag_prob + prob_bag2_b * bag_prob

# Bayes theorem
prob_bag1_black = (prob_bag1_b * bag_prob) / ball_b
prob_bag2_black = 1.0 - prob_bag1_black
print("Bag 1 Black Probability: {:.2f}".format(prob_bag1_black))
print("Bag 2 Black Probability: {:.2f}".format(prob_bag2_black))

Bag 1 Probability: 0.33
Bag 2 Probability: 0.67
Bag 1 White Probability: 0.33
Bag 2 White Probability: 0.67
Bag 1 Black Probability: 0.64
Bag 2 Black Probability: 0.36


### <font color=blue>Question 2 Part B</font>

Consider again the same scenario as in part A, except that Alice now selects 10 balls randomly with replacement from the selected bag. She keeps a record of the colours of the balls and then presents this record to Bob.

**i)** Write code to simulate Alice's selection of the 10 balls. (Hint: you can use a list to record the colour of each ball. The output should display the list.)  &emsp; **\[8 marks\]**

Mark breakdown: 
- 1 mark for selecting the bag
- 4 marks for selecting the white or black balls 
- 3 marks for keeping a list of the colours selected and displaying them

In [88]:
# this is the version without the list, but as list was requested
# I made another one with a list below

###########################################################################
# Normal Version
###########################################################################

print("Normal Version - Randomised\n")

# Copied code from previous bag selection for new bag selection each time
random_bag = np.random.random()
result = ""

if random_bag < Coin:
    result = Heads
else:
    result = Tails

bag = result
print("Selected Bag", bag, "\n")


for i in range(10):
    random_ball = np.random.random()
    if bag == 1:

        if random_ball <= 0.3:
            colour = "White Ball" 
        else:
            colour = "Black Ball"

    elif bag == 2:

        if random_ball <= 0.6:
            colour = "White Ball" 
        else:
            colour = "Black Ball"

    print(colour)

print("\nor\n")

###########################################################################
# List version
###########################################################################

import pandas as pd

print("List Version - Re-Randomised\n")

# Copied code from previous bag selection for new bag selection each time
random_bag = np.random.random()
result = ""

if random_bag < Coin:
    result = Heads
else:
    result = Tails

bag = result
print("Selected Bag", bag, "\n")


# Alice's selection of balls
alice_selection = []

# 10 times
for i in range(10):
    
    random_ball = np.random.random()
    
    if bag == 1:
        if random_ball <= 0.3:
            alice_selection.append("White Ball") 
        else:
            alice_selection.append("Black Ball")
            
    elif bag == 2: 
        if random_ball <= 0.6: 
            alice_selection.append("White Ball")
        else: 
            alice_selection.append("Black Ball")

            
# Displays 10 balls from Alice's selection
display(alice_selection)

Normal Version - Randomised

Selected Bag 2 

Black Ball
Black Ball
White Ball
Black Ball
White Ball
White Ball
Black Ball
White Ball
Black Ball
White Ball

or

Diplayed List Version - Re-Randomised

Selected Bag 1 



['Black Ball',
 'White Ball',
 'Black Ball',
 'Black Ball',
 'Black Ball',
 'Black Ball',
 'Black Ball',
 'White Ball',
 'Black Ball',
 'Black Ball']

**ii)** Bob now proceeds to work out the probability that the selected bag was bag 1 and the probability that it was bag 2 after each outcome. Provide code to enable him to determine these probabilities. Your code should determine the probabilities after one ball is selected, after two balls are selected, ..., after ten balls are selected and present the output in a table.  &emsp; **\[12 marks\]**

Mark breakdown: 
- 4 marks for calculation of probabilities
- 4 marks for appropriate iteration and selection
- 4 marks for displaying correct output in a table

In [72]:
import pandas as pd

# Bayes theorem 
selected_bag1 = (bag * Coin) / bag
selected_bag2 = 1.0 - selected_bag1
print("Bag 1 Probability: {:.2f}".format(selected_bag1))
print("Bag 2 Probability: {:.2f}".format(selected_bag2))

# Bayes theorem
prob_bag1_w2 = (prob_bag1_w * bag_prob) / ball_w
prob_bag2_w2 = 1.0 - prob_bag1_w2
print("Bag 1 Ball 2 White Probability: {:.2f}".format(prob_bag1_w2))
print("Bag 2 Ball 2 White Probability: {:.2f}".format(prob_bag2_w2))

# Bayes theorem
prob_bag1_b2 = (prob_bag1_b * bag_prob) / ball_b
prob_bag2_b2 = 1.0 - prob_bag1_b2
print("Bag 1 Ball 2 Black Probability: {:.2f}".format(prob_bag1_b2))
print("Bag 2 Ball 2 Black Probability: {:.2f}".format(prob_bag2_b2))


# Array list and table display

Bag_Probabilities_List = []

for i in range(3):
    # Bayes Theorem
    prob_bag1 = (prob_bag1_w * bag_prob) / ball_w
    prob_bag2 = 1.0 - prob_bag1
    
    Bag_Probabilities_List.append(prob_bag1)
    Bag_Probabilities_List.append(prob_bag2)

    ball_w2 = ball_w * bag_prob + ball_w * bag_prob
    ball_b2 = ball_b * bag_prob + ball_w * bag_prob
    
    prob_bag1 = (ball_w2 * bag_prob) / ball_b2
    prob_bag2 = 1.0 - prob_bag1

    Bag_Probabilities_List.append(prob_bag1)
    Bag_Probabilities_List.append(prob_bag2)

table = pd.DataFrame(Bag_Probabilities_List)
display(table.head(10))

Bag 1 Probability: 0.50
Bag 2 Probability: 0.50
Bag 1 Ball 2 White Probability: 0.70
Bag 2 Ball 2 White Probability: 0.30
Bag 1 Ball 2 Black Probability: 0.47
Bag 2 Ball 2 Black Probability: 0.53


0
0  0.696917
1  0.303083
2  0.500000
3  0.500000
4  0.696917
5  0.303083
6  0.500000
7  0.500000
8  0.696917
9  0.303083

## <font color=blue>Question 3: Statistics</font>

For this question you will need to use the file `tips` dataset, which is included as part of the [Seaborn library](https://seaborn.pydata.org/).


**i)**	Load the dataset, display the first 10 entries in it and provide summary information including the mean, standard deviation and maximum and minimum for each numerical variable in the dataset. &emsp; **\[6 marks\]**

Mark breakdown:
- 2 marks for loading dataset
- 2 marks for displaying 10 entries 
- 2 marks for summary stats

In [466]:
import seaborn as sb

tips = sb.load_dataset("tips")
print("\nTips First 10 Entries\n")
display(tips.head(10))

print("\nTips Summary\n")
display(tips.describe())


Tips First 10 Entries



total_bill   tip     sex smoker  day    time  size
0       16.99  1.01  Female     No  Sun  Dinner     2
1       10.34  1.66    Male     No  Sun  Dinner     3
2       21.01  3.50    Male     No  Sun  Dinner     3
3       23.68  3.31    Male     No  Sun  Dinner     2
4       24.59  3.61  Female     No  Sun  Dinner     4
5       25.29  4.71    Male     No  Sun  Dinner     4
6        8.77  2.00    Male     No  Sun  Dinner     2
7       26.88  3.12    Male     No  Sun  Dinner     4
8       15.04  1.96    Male     No  Sun  Dinner     2
9       14.78  3.23    Male     No  Sun  Dinner     2


Tips Summary



total_bill         tip        size
count  244.000000  244.000000  244.000000
mean    19.785943    2.998279    2.569672
std      8.902412    1.383638    0.951100
min      3.070000    1.000000    1.000000
25%     13.347500    2.000000    2.000000
50%     17.795000    2.900000    2.000000
75%     24.127500    3.562500    3.000000
max     50.810000   10.000000    6.000000

**ii)**	Display information about the five highest total bills in the dataset and the five smallest tips.  &emsp; **\[4 marks\]**

In [387]:
# 5 Highest Total Bills
print("5 Highest Total Bills\n")
five_highest_total_bills = tips.nlargest(5, ["total_bill"])
display(five_highest_total_bills)

# 5 Smallest Tips
("5 Smallest Tips\n")
five_smallest_tips = tips.nsmallest(5, ["tip"])
display(five_smallest_tips)

5 Highest Total Bills



total_bill    tip   sex smoker  day    time  size
170       50.81  10.00  Male    Yes  Sat  Dinner     3
212       48.33   9.00  Male     No  Sat  Dinner     4
59        48.27   6.73  Male     No  Sat  Dinner     4
156       48.17   5.00  Male     No  Sun  Dinner     6
182       45.35   3.50  Male    Yes  Sun  Dinner     3

'5 Smallest Tips\n'

total_bill   tip     sex smoker  day    time  size
67         3.07  1.00  Female    Yes  Sat  Dinner     1
92         5.75  1.00  Female    Yes  Fri  Dinner     2
111        7.25  1.00  Female     No  Sat  Dinner     1
236       12.60  1.00    Male    Yes  Sat  Dinner     2
0         16.99  1.01  Female     No  Sun  Dinner     2

**iii)**	Determine the median value and interquartile range for the tips.  &emsp; **\[4 marks\]**

In [411]:
print("Median and Interquartile Range for Tips\n")
tips_median = tips['tip'].median()
print("Tips Median Value = {:.2f}".format(tips_median))

tips_Q1 = tips['tip'].quantile(0.25)
print("Tips Lower Quartile (Q1) = {:.2f}".format(tips_Q1))

tips_Q3 = tips['tip'].quantile(0.75)
print("Tips Upper Quartile (Q3) = {:.2f}".format(tips_Q3))

tips_IQR = tips_Q3 - tips_Q1
# print("\nTips IQR = Q3 - Q1")
# print("\nTips IQR = 3.56 - 2.00")

print("Tips Interquartile Range (IQR) = {:.2f}".format(tips_IQR))

Median and Interquartile Range for Tips

Tips Median Value = 2.90
Tips Lower Quartile (Q1) = 2.00
Tips Upper Quartile (Q3) = 3.56
Tips Interquartile Range (IQR) = 1.56


**iv)**	Find any outliers in the tips using the 1.5(IQR) rule. (For full marks the total bill as well as the tip should be identified for each outlier.)  &emsp; **\[6 marks\]**

In [393]:
# 1.5(IQR) rule

tips_lower_limit = tips_Q1 - tips_IQR * 1.5
tips_upper_limit = tips_Q3 + tips_IQR * 1.5

# Tip outliers
tip_outliers = tips[(tips.tip<tips_lower_limit)|(tips.tip>tips_upper_limit)]
display(tip_outliers)
  
# Total Bill Outliers
bill_outliers = tips[(tips.total_bill<tips_lower_limit)|(tips.total_bill>tips_upper_limit)]
display(bill_outliers)

total_bill    tip     sex smoker   day    time  size
23        39.42   7.58    Male     No   Sat  Dinner     4
47        32.40   6.00    Male     No   Sun  Dinner     4
59        48.27   6.73    Male     No   Sat  Dinner     4
141       34.30   6.70    Male     No  Thur   Lunch     6
170       50.81  10.00    Male    Yes   Sat  Dinner     3
183       23.17   6.50    Male    Yes   Sun  Dinner     4
212       48.33   9.00    Male     No   Sat  Dinner     4
214       28.17   6.50  Female    Yes   Sat  Dinner     3
239       29.03   5.92    Male     No   Sat  Dinner     3

total_bill   tip     sex smoker   day    time  size
0         16.99  1.01  Female     No   Sun  Dinner     2
1         10.34  1.66    Male     No   Sun  Dinner     3
2         21.01  3.50    Male     No   Sun  Dinner     3
3         23.68  3.31    Male     No   Sun  Dinner     2
4         24.59  3.61  Female     No   Sun  Dinner     4
..          ...   ...     ...    ...   ...     ...   ...
239       29.03  5.92    Male     No   Sat  Dinner     3
240       27.18  2.00  Female    Yes   Sat  Dinner     2
241       22.67  2.00    Male    Yes   Sat  Dinner     2
242       17.82  1.75    Male     No   Sat  Dinner     2
243       18.78  3.00  Female     No  Thur  Dinner     2

[242 rows x 7 columns]

**v)**	Let $Y$ represent the tip and $X$ the total bill. Use linear regression to find a line of best fit between $X$ and $Y$. You should present a scatterplot of $X$ and $Y$ along with the line of best fit.   &emsp; **\[10 marks\]**

<font color=blue>For full marks you should also present the coefficients for the regression line in the form $Y = aX + b$ and the $R^2$ value to indicate how well the line fits the data.</font>

Mark breakdown: 
- 5 for calcuation of coefficients (including $R$)
- 3 for figure
- 2 for displaying equation and $R^2$

In [469]:
import matplotlib.pyplot as mpl
import pandas as pd
from scipy.stats import linregress

X = tips['total_bill']
Y = tips['tip']

# calcuation of coefficients
A, B, R, P, stderr = linregress(X,Y)

print("\nSlope (A) = {:.2f}".format(A)) 
print("\nIntercept (B) = {:.2f}".format(B))
print("\nr_value (R^2) = {:.2f}".format(R*2))
print("\np_value (P) = {:.2f}".format(P))
print("\nstd_err (stderr) = {:.2f}".format(stderr))
print("\n")

# Graph
mpl.scatter(X,Y)

xLine = np.linspace(0,50,15)
yLine = A * xLine + B

mpl.plot(xLine, yLine, color='Red')
mpl.show()


Slope (A) = 0.11

Intercept (B) = 0.92

r_value (R^2) = 1.35

p_value (P) = 0.00

std_err (stderr) = 0.01


